# Week 6 - Data Cleansing & Manipulation
---

Mentoring Session - Job Preparation Program - Pacmann AI

In [1]:
# Please load this library
import numpy as np
import pandas as pd

# Task 1. Merge Transactions Data Across Branches

---

## Task Descriptions
---

- Toko Serba Ada has several branches across the country.
- Toko Serba Ada manager wants to merge the transactions data across branches.
- Your task is to create a function to join multiple transaction files.
- Download the transactions files [here](https://drive.google.com/drive/folders/1bJ5EWEHwx3xXlSLVyUYjjK2D6v_br-hb?usp=sharing).

## Detail function
---

- Create a function called by `import_data`.
- The function only needs one input, `filenames` (`list`), a list of transactions data files.
- The `import_data` function will join every data listed on the filenames as a Pandas DataFrame.

## Examples
---

**Input**

```python
# Masukkan input
filenames = [
    'branch_A.xlsx',
    'branch_B.csv',
    'branch_C.csv'
]

# Import data
data = import_data(filenames = filenames)

# Validasi hasil
print('Data shape:', data.shape)
data.head(5)
```

**Output**
```
Data shape: (1000, 17)
```

## Answer
---

- Provide the code for solving the problem
- **Make sure your function follows the `Detail Function`**

In [25]:
def import_data(filenames):
    """
    Takes multiple files with .xlsx and .csv extensions and combined all of
    them into a single pandas.DataFrame.
    """
    from pathlib import Path
    dfs = []
    idl = []
    for name in filenames:
        # export the extension    
        ext = Path(name).suffix
        # store the read data frame inside a list
        if ext == ".xlsx":
            data = pd.read_excel(name)
        else:
            data = pd.read_csv(name, delimiter=';')

        dfs.append(data)
        # store index length of each data frame for later verification
        idl.append(len(data.index))
    
    # concat all the list available using pd.concat()
    main_data = pd.concat(dfs)

    # verify the data by totalling the index length
    if len(main_data.index) == sum(idl):
        return main_data
    else:
        raise ImportError('There is something wrong about the import process')

filenames = ['branch_A.xlsx', 'branch_B.csv', 'branch_C.csv']
data = import_data(filenames=filenames)
data.shape

(1000, 17)

# Task 2. Get the Unwatched Movie

---

## Task Descriptions
---

- You are a data analyst in a movie industry
- The product team ask you to recommend something new for a user to watch.
- You easily think of recommending the unwatched movies for a specific user Id.
- To recommend the unwatched movies nicely in the website, the engineering team needs you to return 3 things
  - `movieId`
  - `title`
  - `genres`
- Your task is to **create a function** to return the unwatched movies from a specific user id based on engineering team requirements.
- You can download your dataset in [here](https://drive.google.com/drive/folders/1HSa7KStIlOS7rXY5ykwGZR6l9P-AJrKj?usp=sharing).
  - `ratings.csv` contains the user activity after watching movies, i.e. give a rating to each movie they watched.
  - `movies.csv` contains the movie metadata (movie ID, title, and genre)
- The dataset originally comes from **MovieLens**

## Detail function
---

- Create a function called `get_unwatched_movie`
- The function needs two input
  - `userId` (`int`): The targeted user ID
  - `config` (`dict`): The configuration files where the engineering team store the user-data and movie metadata. Example

  ```python
  config = {
      'path': {
          'user_data': 'ratings.csv',
          'metadata': 'movies.csv'
      }
  }
  ```

- The function return an output in pandas DataFrame type with `movieId` as an index and two columns of `title` and `genres`.

## Examples
---

**Define the Configuration Variable**

```python
# Define CONFIG variable
CONFIG = {
    'path': {
        'user_data': 'ratings.csv',
        'metadata': 'movies.csv'
    }
}
```

---
**Input 1**

```python
# Cari unwatched data untuk userId = 3
unwatched_data = get_unwatched_movie(userId = 3,
                                     config = CONFIG)

print('Data shape:', unwatched_data.shape)
unwatched_data.sample(n=5, random_state=42)
```

**Output 1**
```
Data shape: (9703, 2)
```

---
**Input 2**

```python
# Cari unwatched data untuk userId = 10
unwatched_data = get_unwatched_movie(userId = 10,
                                     config = CONFIG)

print('Data shape:', unwatched_data.shape)
unwatched_data.sample(n=5, random_state=42)
```

**Output 2**
```
Data shape: (9602, 2)
```

---
**Input 3**

```python
# Cari unwatched data untuk userId = 3
unwatched_data = get_unwatched_movie(userId = 3,
                                     config = CONFIG)

print('Data shape:', unwatched_data.shape)
unwatched_data.sample(n=5, random_state=42)
```

**Output 3**
```
Data shape: (9402, 2)
```

## Answer
---

- Provide the code for solving the problem
- **Make sure your function follows the `Detail Function`**

In [63]:
CONFIG = {
    'path': {
        'user_data': 'ratings.csv',
        'metadata': 'movies.csv'
    }
}

def get_unwatched_movie(userId, config=CONFIG):
    # load data
    user_data = pd.read_csv(config["path"]["user_data"])
    metadata = pd.read_csv(config["path"]["metadata"])
    # select unique watched movieId
    watched_movieIds = user_data[user_data['userId'] == userId]['movieId'].unique()
    # separate unwatched movies from the watched ones
    unwatched_movies = metadata[~metadata['movieId'].isin(watched_movieIds)]
    unwatched_movies.set_index('movieId', inplace=True)
    return unwatched_movies

In [64]:
# get unwatched movies for userId 3
unwatched_movies = get_unwatched_movie(userId=3)
print(f"Data shape: {unwatched_movies.shape}")
unwatched_movies.sample(5, random_state=42)

Data shape: (9703, 2)

,title,genres
movieId,,
553,Tombstone (1993),Action|Drama|Western
85025,"Eagle, The (2011)",Adventure|Drama
78836,Enter the Void (2009),Drama
2296,"Night at the Roxbury, A (1998)",Comedy
46970,Talladega Nights: The Ballad of Ricky Bobby (2...,Action|Comedy

In [65]:
# get unwatched movies for userId 10
unwatched_movies = get_unwatched_movie(userId=10)
print(f"Data shape: {unwatched_movies.shape}")
unwatched_movies.sample(5, random_state=42)

Data shape: (9602, 2)

,title,genres
movieId,,
1797,Everest (1998),Documentary|IMAX
179819,Star Wars: The Last Jedi (2017),Action|Adventure|Fantasy|Sci-Fi
77266,Disgrace (2008),Drama
26003,Night and Fog (Nuit et brouillard) (1955),Crime|Documentary|War
54686,"Last Legion, The (2007)",Action|Adventure|Fantasy|War

# Task 3. Get the House Recommendation

---

## Task Descriptions
---

- Assume you work as a Data Analyst in Travelio.
- The product team request you to give its users housing recommendations based on their current location and housing preferences.
- Please create a function to answer the product team request.
- You can find the dataset [here](https://drive.google.com/file/d/1D5phg8q0MiX4lRKlEaBWHT07MoEgEr28/view?usp=sharing).
- **Note**: The dataset is scrapped by Pacmann from the Travelio website for educational purposes only.

## Detail function
---

- Create a function called by `get_user_recommendation` that return the top-$n$ housing recommendation for a specific user location & preferences sorted by the nearest distance between user location and house location.
- The function needs three input, i.e.
    - `n` (`int`): the maximum number of recommendation.
    - `user_config` (`dict`): the user configuration data. It contains the user preferences and user current location.
    - `data_config` (`dict`): the data configuration that contains the housing data path.
- The output is a dataframe type with similar data columns to the dataset.
---
- We filter using 5 preferences, that is
  - `property_type`. It should return `apartment` or `house`.
  - `size`. It should return houses that is **larger than or equal to** the given `size`.
  - `capacity`. It should return houses that is **more than or equal to** the given `capacity`.
  - `is_furnished`. It should return `Full Furnished` or `Unfurnished`.
  - `yearly_price`. It should return houses that is **less than or equal to** the given `yearly_price` rent
- If user fill nothing (`None`), then you should not filter anything.
---
- Please use the **Haversine** distance to calculate the distance between user and houses.
- We intentionally not giving you the Haversine distance formula. Please explore it by yourself.

## Examples

---
**Input 1**

```python
# Define the user data
user_config = {
    'preferences': {
        'property_type': None,
        'size': 30.0,
        'capacity': 2,
        'is_furnished': 'Full Furnished',
        'yearly_price': 50000000
    },
    'location': {
        # Dekat Bintaro Plaza
        'latitude': -6.2734,
        'longitude': 106.7364
    }
}

data_config = {
    'path': 'travelio_dki_jakarta.csv'
}

# Run the function
user_recommendation = get_user_recommendation(n = 10,
                                              user_config = user_config,
                                              data_config = data_config)

# Validate
print('Data Shape:', user_recommendation.shape)
user_recommendation
```

**Output 1**
```
Data Shape: (10, 16)
```

---
**Input 2**

```python
# Define the user data
user_config = {
    'preferences': {
        'property_type': None,
        'size': 45.0,
        'capacity': 4,
        'is_furnished': None,
        'yearly_price': 25000000
    },
    'location': {
        # Dekat Monumen Nasional (Monas)
        'latitude': -6.1792,
        'longitude': 106.8265
    }
}

data_config = {
    'path': 'travelio_dki_jakarta.csv'
}

# Run the function
user_recommendation = get_user_recommendation(n = 10,
                                              user_config = user_config,
                                              data_config = data_config)

# Validate
print('Data Shape:', user_recommendation.shape)
user_recommendation
```

**Output 2**
```
Data Shape: (10, 16)
```

---
**Input 3**

```python
# Define the user data
user_config = {
    'preferences': {
        'property_type': None,
        'size': 60.0,
        'capacity': 4,
        'is_furnished': None,
        'yearly_price': 25000000
    },
    'location': {
        # Dekat Kota Tua Jakarta
        'latitude': -6.1378,
        'longitude': 106.8144
    }
}

data_config = {
    'path': 'travelio_dki_jakarta.csv'
}

# Run the function
user_recommendation = get_user_recommendation(n = 10,
                                              user_config = user_config,
                                              data_config = data_config)

# Validate
print('Data Shape:', user_recommendation.shape)
user_recommendation
```

**Output 3**
```
Data Shape: (6, 16)
```

## Answer
---

- Provide the code for solving the problem
- **Make sure your function follows the `Detail Function`**

In [ ]:
import math

# haversine function
def haversine(lat1, lon1, lat2, lon2):
    """
    https://www.geeksforgeeks.org/haversine-formula-to-find-distance-between-two-points-on-a-sphere/
    """
    dLat = (lat2 - lat1) * math.pi / 180.0
    dLon = (lon2 - lon1) * math.pi / 180.0
    lat1 = lat1 * math.pi / 180.0
    lat2 = lat2 * math.pi / 180.0
    a = (pow(math.sin(dLat/2), 2) + pow(math.sin(dLon/2), 2) * math.cos(lat1) * math.cos(lat2))
    rad = 6371 # earth radius in km
    c = 2 * math.asin(math.sqrt(a))
    return rad * c

def get_user_recommendation(n, user_config, data_config):
    # load data from csv
    data = pd.read_csv(data_config["path"])

    # load user preferences
    user_pref = user_config["preferences"]
    user_loc = user_config["location"]
    # compare with property_type (house/apartment/none)
    property_type = "" if user_pref["property_type"] is None else user_pref["property_type"]
    prop_cond = True if property_type == "" else data.property_type == property_type
    # compare with size (actual num/none)
    size = 0 if user_pref["size"] is None else user_pref["size"]
    size_cond = data['size'] >= size
    # compare with capacity (actual num/none)
    capacity = 0 if user_pref["capacity"] is None else user_pref["capacity"]
    capacity_cond = data['capacity'] >= capacity
    # compare with is_furnished (Full Furnished/Unfurnished/none)
    is_furnished = "" if user_pref["is_furnished"] is None else user_pref["is_furnished"]
    furnish_cond = True if is_furnished == "" else data['is_furnished'] == is_furnished
    # compare with yearly_price (actual num/none)
    yearly_price = 0 if user_pref["yearly_price"] is None else user_pref["yearly_price"]
    yearly_cond = data['yearly_price'] <= yearly_price
    lat = user_loc["latitude"]
    long = user_loc["longitude"]

    # get data by user preferences
    data_by_preferences = data[prop_cond & size_cond & capacity_cond & furnish_cond & yearly_cond].copy()
    data_by_preferences['distance_km'] = data_by_preferences.apply(
        lambda row: haversine(lat, long, row['latitude'], row['longitude']),
        axis=1
    )
    data_by_preferences.sort_values(by='distance_km', inplace=True)
    
    # remove distance_km column
    data_by_preferences.drop(columns='distance_km', inplace=True)
    
    return data_by_preferences.head(n)

In [82]:
user_config = {
    'preferences': {
        'property_type': None,
        'size': 30.0,
        'capacity': 2,
        'is_furnished': 'Full Furnished',
        'yearly_price': 50000000
    },
    'location': {
        # Dekat Bintaro Plaza
        'latitude': -6.2734,
        'longitude': 106.7364
    }
}

data_config = {
    'path': 'travelio_dki_jakarta.csv'
}

# Run the function
user_recommendation = get_user_recommendation(n = 3,
                                              user_config = user_config,
                                              data_config = data_config)

# Validate
print('Data Shape:', user_recommendation.shape)
user_recommendation

Data Shape: (3, 16)

,ads_name,property_type,apartment_name,area,region,city,latitude,longitude,bedrooms,bathrooms,size,is_furnished,capacity,rating,yearly_price,property_management_type
26,Homey and Well Designed 2BR at Bintaro Park Vi...,apartment,Apartemen Bintaro Park View,Pesanggrahan,DKI Jakarta,Jakarta,-6.25802,106.758716,2,1,37.50,Full Furnished,3,5.0,44950000,TPM
2505,2BR Apartment Bintaro Park View near Bintaro P...,apartment,Apartemen Bintaro Park View,Pesanggrahan,DKI Jakarta,Jakarta,-6.25802,106.758716,2,1,30.55,Full Furnished,3,4.8,42375000,TPM
1330,Homey 2BR at Bintaro Park View Apartment By Tr...,apartment,Apartemen Bintaro Park View,Pesanggrahan,DKI Jakarta,Jakarta,-6.25802,106.758716,2,1,36.00,Full Furnished,3,NaN,44123527,TPM

In [83]:
user_config = {
    'preferences': {
        'property_type': None,
        'size': 45.0,
        'capacity': 4,
        'is_furnished': None,
        'yearly_price': 25000000
    },
    'location': {
        # Dekat Monumen Nasional (Monas)
        'latitude': -6.1792,
        'longitude': 106.8265
    }
}

data_config = {
    'path': 'travelio_dki_jakarta.csv'
}

# Run the function
user_recommendation = get_user_recommendation(n = 5,
                                              user_config = user_config,
                                              data_config = data_config)

# Validate
print('Data Shape:', user_recommendation.shape)
user_recommendation

Data Shape: (5, 16)

,ads_name,property_type,apartment_name,area,region,city,latitude,longitude,bedrooms,bathrooms,size,is_furnished,capacity,rating,yearly_price,property_management_type
1209,Unfurnished 2BR at Gading Greenhill Apartment ...,apartment,Apartemen Gading Greenhill,Kelapa Gading,DKI Jakarta,Jakarta,-6.147627,106.916258,2,1,48.37,Unfurnished,4,5.0,25000000,REALTY
707,2BR Unfurnished Apartment at Gading Greenhill ...,apartment,Apartemen Gading Greenhill,Kelapa Gading,DKI Jakarta,Jakarta,-6.147630,106.916262,2,1,48.37,Unfurnished,4,NaN,22999999,REALTY
3264,Unfurnished 2BR House at Jakarta Timur near Ha...,house,NaN,Halim Perdanakusuma,DKI Jakarta,Jakarta,-6.266901,106.877731,2,2,90.00,Unfurnished,4,NaN,25000000,REALTY
3260,Strategic 3BR House in Cilincing By Travelio R...,house,NaN,Jakarta Utara,DKI Jakarta,Jakarta,-6.116879,106.927530,3,3,108.00,Full Furnished,6,NaN,24000000,REALTY
3257,Unfurnished 4BR House at Tanah Merdeka Cilinci...,house,NaN,Jakarta Utara,DKI Jakarta,Jakarta,-6.106318,106.920193,4,1,93.00,Unfurnished,9,NaN,22000000,REALTY

In [86]:
user_config = {
    'preferences': {
        'property_type': None,
        'size': 60.0,
        'capacity': 4,
        'is_furnished': None,
        'yearly_price': 25000000
    },
    'location': {
        # Dekat Kota Tua Jakarta
        'latitude': -6.1378,
        'longitude': 106.8144
    }
}

data_config = {
    'path': 'travelio_dki_jakarta.csv'
}

# Run the function
user_recommendation = get_user_recommendation(n = 10,
                                              user_config = user_config,
                                              data_config = data_config)

# Validate
print('Data Shape:', user_recommendation.shape)
user_recommendation

Data Shape: (6, 16)

,ads_name,property_type,apartment_name,area,region,city,latitude,longitude,bedrooms,bathrooms,size,is_furnished,capacity,rating,yearly_price,property_management_type
3257,Unfurnished 4BR House at Tanah Merdeka Cilinci...,house,NaN,Jakarta Utara,DKI Jakarta,Jakarta,-6.106318,106.920193,4,1,93.0,Unfurnished,9,NaN,22000000,REALTY
3260,Strategic 3BR House in Cilincing By Travelio R...,house,NaN,Jakarta Utara,DKI Jakarta,Jakarta,-6.116879,106.927530,3,3,108.0,Full Furnished,6,NaN,24000000,REALTY
3259,Unfurnished 2BR House at Malaka 1 Cilincing By...,house,NaN,Jakarta Utara,DKI Jakarta,Jakarta,-6.137113,106.956038,2,1,60.0,Unfurnished,4,NaN,23000000,REALTY
3264,Unfurnished 2BR House at Jakarta Timur near Ha...,house,NaN,Halim Perdanakusuma,DKI Jakarta,Jakarta,-6.266901,106.877731,2,2,90.0,Unfurnished,4,NaN,25000000,REALTY
3265,Unfurnished 2BR House at Kebagusan Wates By Tr...,house,NaN,Kebagusan,DKI Jakarta,Jakarta,-6.318913,106.825159,2,1,70.0,Unfurnished,4,NaN,25000000,REALTY
3262,Unfurnished 2BR House at Belly Pekayon By Trav...,house,NaN,Pasar Rebo,DKI Jakarta,Jakarta,-6.332795,106.865617,2,2,100.0,Unfurnished,4,NaN,24000000,REALTY

# Task 4. Export the Promising State

---

## Task Descriptions
---

- Assumed you are a data analyst in Amazon.
- Your supervisor ask you to export a promising state sales data based on its market share to a .csv files, thus each state representatives can analyst the sales data further.
- A promising state is a state that has its market share bigger or equal to a specified threshold.
- The market share of a specific state is defined as number of order on a specific state / total order.
- Write a function to help your supervisor!
- Download your data in [here](https://drive.google.com/file/d/1oRAPo7ZST2i_pHAIWP2_KoLraniUwyME/view?usp=sharing).
- The actual data source is in [here](https://www.kaggle.com/datasets/thedevastator/unlock-profits-with-e-commerce-sales-data?select=Amazon+Sale+Report.csv).

## Detail function
---

- Create a function called by `export_promising_state`
- This function needs two inputs
  - `config_file` (`dict`) contains the input and output path
  - `thresh` (`float`) contains the given market share threshold.
- This function returns nothing.
- If you cannot find any promising state based on the given threshold, then print `No promising state`.
- If you can find promising state,
  - First, drop column `index` and `Unnamed: 22` from the promising data.
  - Save the promising data with format: `folder_path` + `state-name` + `-sales-reports.csv`, e.g.: `sales_data/telangana-sales-reports.csv`
  - Write the prompt after successfully exporting data that includes the state market share and state sales data shape.

## Examples
---

**Define the Configuration Variable**

```python
# Define CONFIG variable
config_file = {
    'path': {
        'input': 'Amazon Sale Report.csv',
        'output': 'sales_data/'
    }
}
```

---
**Input 1**

```python
# Input 1
export_promising_state(config_file = config_file,
                       thresh = 0.10)
```

**Output 1**
```
Data of state "karnataka" was successfully exported into "sales_data/karnataka-sales-reports.csv"
  - State market share : 13.43 %
  - Data shape         : (17326, 22)

Data of state "maharashtra" was successfully exported into "sales_data/maharashtra-sales-reports.csv"
  - State market share : 17.26 %
  - Data shape         : (22260, 22)
```

Example of the created files: <br>
<img src="https://drive.google.com/uc?id=1C1r8SKoRHbKX0upPl5VDrzuf4Mi0joiC"/>

---
**Input 2**

```python
# Input 2
export_promising_state(config_file = config_file,
                       thresh = 0.05)
```

**Output 2**
```
Data of state "telangana" was successfully exported into "sales_data/telangana-sales-reports.csv"
  - State market share : 8.78 %
  - Data shape         : (11330, 22)

Data of state "kerala" was successfully exported into "sales_data/kerala-sales-reports.csv"
  - State market share : 5.11 %
  - Data shape         : (6585, 22)

Data of state "delhi" was successfully exported into "sales_data/delhi-sales-reports.csv"
  - State market share : 5.40 %
  - Data shape         : (6967, 22)

Data of state "uttar pradesh" was successfully exported into "sales_data/uttar pradesh-sales-reports.csv"
  - State market share : 8.25 %
  - Data shape         : (10638, 22)

Data of state "karnataka" was successfully exported into "sales_data/karnataka-sales-reports.csv"
  - State market share : 13.43 %
  - Data shape         : (17326, 22)

Data of state "tamil nadu" was successfully exported into "sales_data/tamil nadu-sales-reports.csv"
  - State market share : 8.90 %
  - Data shape         : (11483, 22)

Data of state "maharashtra" was successfully exported into "sales_data/maharashtra-sales-reports.csv"
  - State market share : 17.26 %
  - Data shape         : (22260, 22)
```

Example of the created files: <br>
<img src="https://drive.google.com/uc?id=1ujeDK87N4MLk1_9Uew4lkIeFA81_DtDw"/>

---
**Input 3**

```python
# Input 3
export_promising_state(config_file = config_file,
                       thresh = 0.4)
```

**Output 3**
```
No promising state
```
<img src=""/>

## Answer
---

- Provide the code for solving the problem
- **Make sure your function follows the `Detail Function`**

In [ ]:
# Write your function in here
# Psst.. You can build as many functions you need.
#        Just make sure the function is
#        - Modular
#        - Clean (easy to read & with docstring)
#        - Can be easily validated

# Task 5.  Clean the AirBnB data
---

## Task Descriptions
---

- You are given a dataset of guests and hosts of AirBnB.
- This dataset contains the review given by a guest (`id`) to the listing.
- You want to analyze the review given by the guests by `neighborhood group`.
- But the data is not clean.
- Please clean the data by
  1. Dropping data with missing value
  2. Removing the unconsitency in `neighborhood group`
  3. Dropping the listing outliers/anomaly.
    - listing with anomaly rent price (please use IQR method to filter the outlier).
    - listing with anomaly `availability 365` (`availability 365` is defined as an indicator of the total number of days the listing is available for during the year)
  4. Drop duplicates data (if any)

**Dataset**
- Please download the dataset in [here](https://drive.google.com/file/d/19zOwcAkd7lTC_djAMgc5u1B7I2iPj5ek/view?usp=sharing)
- The actual data source is [here](https://www.kaggle.com/datasets/arianazmoudeh/airbnbopendata)

## Expected Output
---

The output should be:
```
Clean data shape: (98174, 26)
```

With the sample of the clean data

<center>
<img src="https://drive.google.com/uc?id=1ZmVMW41RbxCuKUcafic5CL9E0JAemdNk">

## Answer
---

- Provide the code for getting the expected output

In [ ]:
# Write your code in here
# Provide your code with sufficient comment on the wrangling processes

# Task 6. Calculate Month-Over-Month Percentage Change in Sales


---

## Task Descriptions
---

- Given a dataset of sales report by date, **calculate the mont-over-month percentage change in sales**.
- The ouput should include the year-month date (YYYY-MM) and percentage change, rounded to the 2nd decimal point, and sorted by `order-date` in ascending order.
- The percentage change column will be populated from the 2nd month forward and can be calculated as
$$
\cfrac
{(\text{this month's sales - last month's sales})}
{\text{last month's sales}} \cdot 100\%
$$

**Dataset**
- Please download the dataset in [here](https://drive.google.com/file/d/13QxDig8cXrT5ErVO2tytYdmksjbH3tep/view?usp=sharing)
- The actual data source is [here](https://www.kaggle.com/datasets/apoorvaappz/global-super-store-dataset)

## Expected Output
---

The output should be:

```
Data Shape: (48, 3)
````

With the first 12 entry of the final data is

<center>
<img src="https://drive.google.com/uc?id=1Qcj_OUVOqfFCwbau0XUJK9URL3BrX86u">

## Answer
---

- Provide the code for getting the expected output

In [ ]:
# Write your code in here
# Provide your code with sufficient comment on the wrangling processes

# Task 7. Time to Purchase Duration


---

## Task Descriptions
---

- Given a dataset of an e-commerce events history in Electronic shop.
- Your task is to
  1. **calculate each user's time to purchase duration** and
  2. **find the tendency of user view-purchase duration** (please use a proper measure of central tendency).
- Time to purchase duration is defined as the time difference between `view` event and `purchase` event. Consider only the earliest view and purchase.
- The ouput should include `user_id` and their `view_purchase_duration` in minutes.

**Dataset**
- Please download the dataset in [here](https://drive.google.com/file/d/1GfFkxIbAivdY8bqbFbARCiyTzIuooKvV/view?usp=sharing)
- The actual data source is [here](https://www.kaggle.com/datasets/mkechinov/ecommerce-events-history-in-electronics-store/data)

## Expected Output
---

The output should be:
```
Data shape : (7847, 2)
Summary of user's view to purchase duration : 4.7 minutes
```

With the sample of final data

<center>
<img src="https://drive.google.com/uc?id=159zrsppCuawgqn9q0e1B63KJzqe9Pvz9">

## Answer
---

- Provide the code for getting the expected output

In [ ]:
# Write your code in here
# Provide your code with sufficient comment on the wrangling processes