In [1]:
import pandas as pd
import seaborn as sns

# Study Case 1: Cleaning Data Film IMBD

In [2]:
movies = pd.read_csv("IMDB_Movies.csv")

movies.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

## Case 1.1: Drop certain columns from the dataset

Columns to drop:

-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [10]:
column_drop = {
    "color",
    "director_facebook_likes",
    "actor_1_facebook_likes",
    "actor_2_facebook_likes",
    "actor_3_facebook_likes",
    "actor_2_name",
    "cast_total_facebook_likes",
    "actor_3_name",
    "duration",
    "facenumber_in_poster",
    "content_rating",
    "country",
    "movie_imdb_link",
    "aspect_ratio",
    "plot_keywords"
}

if column_drop.issubset(movies.columns):
    movies = movies.drop(list(column_drop), axis=1)

movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,,NaN,NaN,NaN,7.1,0

## Case 1.2: Identify missing value percentage on each column

In [12]:
movies.isnull().sum().sort_values(ascending=False)/len(movies)*100

gross                     17.529248
budget                     9.756098
title_year                 2.141582
director_name              2.062265
num_critic_for_reviews     0.991473
num_user_for_reviews       0.396589
language                   0.277613
actor_1_name               0.138806
genres                     0.000000
movie_title                0.000000
num_voted_users            0.000000
imdb_score                 0.000000
movie_facebook_likes       0.000000
dtype: float64

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   director_name           4939 non-null   object
 1   num_critic_for_reviews  4993 non-null   float64
 2   gross                   4159 non-null   float64
 3   genres                  5043 non-null   object
 4   actor_1_name            5036 non-null   object
 5   movie_title             5043 non-null   object
 6   num_voted_users         5043 non-null   int64
 7   num_user_for_reviews    5023 non-null   object
 8   language                5029 non-null   object
 9   budget                  4551 non-null   float64
 10  title_year              4935 non-null   float64
 11  imdb_score              5043 non-null   float64
 12  movie_facebook_likes    5043 non-null   int64
dtypes: float64(5), int64(2), object(6)
memory usage: 512.3+ KB